package example:gpio;

interface general {
    type pin-number = u32; // Type alias for GPIO pin number
}

interface digital {
    use general.{pin-number};

    // Enum types for GPIO pin states
    enum pin-state {
        high,
        low
    }

    // Digital Output Pin resource, describes the functionallity of a general digital output pin
    // Sets the pin state to 'high' or 'low'
    resource digital-out-pin {
        get-pin-nr: func() -> pin-number;

        set-state: func(state: pin-state);

        set-high: func();
        set-low: func();
        toggle: func();
    }

    // Digital Input Pin resource, describes the functionallity of a general digital input pin
    // Reads the pin and outputs 'high' or 'low'
    resource digital-in-pin {
        get-pin-nr: func() -> pin-number;

        read: func() -> pin-state;

        is-high: func() -> bool;
        is-low: func() -> bool;

        wait-until-state: func(state: pin-state);
        wait-until-high: func();
        wait-until-low: func();

        wait-until-falling-edge: func();
        wait-until-rising-edge: func();
    }

    // Functions to acquire certain GPIO pins configured in the desired mode
    get-digital-in: func(pin-nr: pin-number) -> result<digital-in-pin, string>;
    get-digital-out: func(pin-nr: pin-number) -> result<digital-out-pin, string>;

    
}

interface analog {
    use general.{pin-number};

    // Analog Output Pin resource, describes the functionallity of a general analog output pin
    // Pins output PWM signals
    // TODO: add frequency change method
    resource analog-out-pin {
        get-pin-nr: func() -> pin-number;

        set-value-raw: func(value: u32);
        set-value: func(value: f64); // 1.0 means max, 0.0 means 0V
    }

    // Analog Input Pin resource, describes the functionallity of a general analog input pin
    // Reads by means of an ADC
    // TODO: add resolution change method
    resource analog-in-pin {
        get-pin-nr: func() -> pin-number;

        read-raw: func() -> u32;
        read: func() -> f64;

        wait-until-above-raw: func(value: u32);
        wait-until-above: func(value: f64); // Errors if value > 0.0 and value > 1.0

        wait-until-below-raw: func(value: u32);
        wait-until-below: func(value: f64); // Errors if value > 0.0 and value > 1.0
    }

    // Functions to acquire certain GPIO pins configured in the desired mode
    get-analog-in: func(pin-nr: pin-number) -> result<analog-in-pin, string>;
    get-analog-out: func(pin-nr: pin-number) -> result<analog-out-pin, string>; // PWM pin
}

interface shutdown {
    graceful-shutdown: func(reason: string);
}

world gpio {
    import digital;
    import analog;

    export shutdown;
}
